name: Code Analysis
on:
  push:

jobs:
  code-analysis:
    name: Code analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Run all lint checks
        uses: plone/code-analysis-action@v2
